filepaths:
  models_path: models/
  data_paths:
    train: 
    val: 
    test: 
  cropped_paths: 
    train: cropped_data/train/
    val: cropped_data/val/
    test: 
  instances_paths:
    train: 
    val: 
    test: 
  verify_progress_paths:
    train: 
    val: 
    test: 
mode: train
crop_options:
  dataset_choice: 
verify_options:
  dataset_choice: 
  remove_extra: 
  reset_progress: 
  verify_save_step: 
  crop_missing: 
train_test_options:
  model_name: ResNeXt-101-32x8d
  load_choice: -1
  pretrained: True
  num_epochs: 20
  batch_size: 16
  image_size: 256
  num_workers: 32
  use_num_worker_mult: True