filepaths:
  models_path: models/
  data_paths:
    train: 
    val: 
    test: 
  cropped_paths: 
    train: 
    val: 
    test: 
  instances_paths:
    train: 
    val: 
    test: 
  verify_progress_paths:
    train: 
    val: 
    test: 
mode: plot
crop_options:
  dataset_choice: 
verify_options:
  dataset_choice: 
  remove_extra: 
  reset_progress: 
  verify_save_step: 
  crop_missing: 
train_test_options:
  model_name: resnet50
  load_choice: 
  pretrained: 
  num_epochs: 
  batch_size: 
  image_size: 
  num_workers: 
  use_num_worker_mult: 